name: Package Updates
on:
  workflow_dispatch: ~
  schedule:
    - cron: 0 10 * * 1 # 10am UTC every Monday

jobs:
  open-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-
      - run: yarn install --immutable
      - run: yarn update-all
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          title: Update all package dependencies
          body: |
            All package dependencies, automatically updated by `ncu`.
          commit-message: Update all package dependencies
          author: icon-bot <67597316+icon-bot@users.noreply.github.com>
          commiter: icon-bot <67597316+icon-bot@users.noreply.github.com>
          delete-branch: 'true'
          branch: icon-bot/package-updates
